# deletes client side only mods (run on server)
rm -f cobblemon-ui-tweaks*.jar
rm -f skinlayers3d-fabric*.jar
rm -f bwncr-fabric*.jar
rm -f BadOptimizations*.jar
rm -f BetterPingDisplay-Fabric*.jar
rm -f BetterGrassify*.jar
rm -f chat_heads*.jar
rm -f cobblemon_knowlogy-fabric*.jar
rm -f continuity*.jar
rm -f Controlling-fabric*.jar
rm -f ctrlq-fabric-mc1*.jar
rm -f cwb-fabric*.jar
rm -f dynamiccrosshair*.jar
rm -f dynamic-fps*.jar
rm -f effective*.jar
rm -f enhancedblockentities*.jar
rm -f entity_texture_features_fabric*.jar
rm -f entityculling-fabric*.jar
rm -f fallingleaves*.jar
rm -f fastquit*.jar
rm -f Highlighter*.jar
rm -f Iceberg*.jar
rm -f iris-fabric*.jar
rm -f lambdynamiclights*.jar
rm -f modmenu*.jar
rm -f modelfix*.jar
rm -f morechathistory*.jar
rm -f moreculling-fabric*.jar
rm -f MouseTweaks-fabric*.jar
rm -f nvidium*.jar
rm -f optigui*.jar
rm -f PresenceFootsteps*.jar
rm -f reeses-sodium-options-fabric*.jar
rm -f rrls-*.jar
rm -f spark-*.jar
rm -f Searchables-fabric*.jar
rm -f simple-health-indicator*.jar
rm -f sodium-fabric*.jar
rm -f sodium-extra-fabric*.jar
rm -f waveycapes-fabric*.jar
rm -f Xaeros_Minimap*.jar
rm -f pv-addon-soundphysics*.jar